// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LikesUpdate struct {
	Added   []int `json:"added"`
	Removed []int `json:"removed"`
}

type PageInfo struct {
	HasPreviousPage bool `json:"hasPreviousPage"`
	HasNextPage     bool `json:"hasNextPage"`
	StartCursor     *int `json:"startCursor"`
	EndCursor       *int `json:"endCursor"`
}

type Rule struct {
	ID      int       `json:"id"`
	User    *User     `json:"user"`
	Created string    `json:"created"`
	Summary string    `json:"summary"`
	Detail  *string   `json:"detail"`
	Likes   *UserPage `json:"likes"`
}

type RulePage struct {
	Rules    []*Rule   `json:"rules"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type User struct {
	ID    int       `json:"id"`
	Name  string    `json:"name"`
	Rules *RulePage `json:"rules"`
	Likes *RulePage `json:"likes"`
}

type UserPage struct {
	Users    []*User   `json:"users"`
	PageInfo *PageInfo `json:"pageInfo"`
}
